# Generated by Django 5.1.7 on 2026-04-20 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_expenses', models.BooleanField(default=True)),
                ('can_access_family_finances', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User section access',
                'verbose_name_plural': 'User section access',
            },
        ),
    ]
