# Generated by Django 5.1.7 on 2026-04-20 14:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Household', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_household', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_finances.household')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllowanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_allowances_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='family_finances.familymember')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_entries', to='family_finances.household')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('significant_purchase', 'Significant purchase'), ('holiday', 'Holiday')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spent_at', models.DateField()),
                ('payer', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('manual_significant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_spend_entries_created', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_entries', to='family_finances.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_entries', to='family_finances.familymember')),
            ],
            options={
                'ordering': ['-spent_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='uniq_family_member_name_per_household'),
        ),
        migrations.AddIndex(
            model_name='allowanceentry',
            index=models.Index(fields=['member', 'received_at'], name='family_fina_member__82b24d_idx'),
        ),
        migrations.AddIndex(
            model_name='allowanceentry',
            index=models.Index(fields=['household', 'received_at'], name='family_fina_househo_5139ce_idx'),
        ),
        migrations.AddIndex(
            model_name='spendentry',
            index=models.Index(fields=['member', 'spent_at'], name='family_fina_member__2a550d_idx'),
        ),
        migrations.AddIndex(
            model_name='spendentry',
            index=models.Index(fields=['household', 'spent_at'], name='family_fina_househo_c23df8_idx'),
        ),
        migrations.AddIndex(
            model_name='spendentry',
            index=models.Index(fields=['household', 'kind', 'spent_at'], name='family_fina_househo_892343_idx'),
        ),
        migrations.AddIndex(
            model_name='spendentry',
            index=models.Index(fields=['household', 'payer', 'spent_at'], name='family_fina_househo_b61aba_idx'),
        ),
    ]
