# Generated by Django 5.1.7 on 2026-07-03 09:37

import django.core.validators
import django.db.models.deletion
import family_finances.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(
                        default=family_finances.models.generate_family_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="family_finances.family",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("family", "name")},
            },
        ),
        migrations.CreateModel(
            name="FamilyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("regular_allowance", "Regular allowance"),
                            ("one_off_personal_expense", "One-off personal expense"),
                            ("shared_family_expense", "Shared family expense"),
                            (
                                "large_parental_contribution",
                                "Large parental contribution",
                            ),
                            (
                                "excluded_non_fairness_expense",
                                "Excluded / non-fairness expense",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("allowance", "Allowance"),
                            ("clothing", "Clothing"),
                            ("education", "Education"),
                            ("travel", "Travel"),
                            ("hobbies", "Hobbies"),
                            ("technology", "Technology"),
                            ("driving_lessons", "Driving lessons"),
                            ("gifts", "Gifts"),
                            ("medical", "Medical"),
                            ("school_essentials", "School essentials"),
                            ("holidays", "Holidays"),
                            ("food", "Food"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("mum", "Mum"),
                            ("dad", "Dad"),
                            ("both", "Both"),
                            ("other", "Other"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("counts_toward_fairness", models.BooleanField(default=True)),
                ("is_large_expense", models.BooleanField(default=False)),
                ("split_between_children", models.BooleanField(default=False)),
                ("recurring", models.BooleanField(default=False)),
                (
                    "recurring_frequency",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("recurring_start_date", models.DateField(blank=True, null=True)),
                ("recurring_end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("receipt_url", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="family_finances.family",
                    ),
                ),
                (
                    "generated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_instances",
                        to="family_finances.familytransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionChildSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_splits",
                        to="family_finances.child",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="family_finances.familytransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["child__name"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=16,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="family_finances.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["family__name", "user__username"],
                "unique_together": {("family", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="familytransaction",
            index=models.Index(
                fields=["family", "date"], name="family_fina_family__a2f3a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familytransaction",
            index=models.Index(
                fields=["family", "category"], name="family_fina_family__d1a1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familytransaction",
            index=models.Index(
                fields=["family", "type"], name="family_fina_family__b51e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familytransaction",
            index=models.Index(
                fields=["family", "recurring"], name="family_fina_family__e29aab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="familytransaction",
            constraint=models.UniqueConstraint(
                fields=("generated_from", "date"),
                name="unique_generated_family_transaction_date",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionchildsplit",
            index=models.Index(
                fields=["child", "transaction"], name="family_fina_child_i_81e14e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionchildsplit",
            unique_together={("transaction", "child")},
        ),
    ]
