# Generated by Django 5.1.7 on 2026-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familytransaction",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("mum", "Mum"),
                    ("dad", "Dad"),
                    ("both", "Both"),
                    ("child", "Child"),
                    ("other", "Other"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="familytransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular_allowance", "Regular allowance"),
                    ("one_off_personal_expense", "One-off personal expense"),
                    ("shared_family_expense", "Shared family expense"),
                    ("large_parental_contribution", "Large parental contribution"),
                    (
                        "excluded_non_fairness_expense",
                        "Excluded / non-fairness expense",
                    ),
                    (
                        "child_paid_personal_transaction",
                        "Child-paid personal transaction",
                    ),
                    ("other", "Other"),
                ],
                max_length=40,
            ),
        ),
    ]
