# Generated by Django 5.1.7 on 2026-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
