import { useEffect, useState } from 'react'
import FamilyLayout from './FamilyLayout'
import { getFamilyFairness } from '../../../api/family'
import { formatCurrency } from './helpers'

export default function FamilyFairness() {
  const [data, setData] = useState(null)
  useEffect(() => { getFamilyFairness().then(setData) }, [])
  if (!data) return <FamilyLayout title="Fairness"><p className="text-gray-500">Loading fairness comparison...</p></FamilyLayout>
  const max = Math.max(...data.children.map((child) => Number(child.counted_total || 0)), 1)
  return <FamilyLayout title="Fairness dashboard"><div className="space-y-6"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="bg-white rounded-2xl border border-gray-200 p-5"><p className="text-sm text-gray-500">Family average</p><p className="text-2xl font-bold text-blue-700">{formatCurrency(data.family_average)}</p></div><div className="bg-white rounded-2xl border border-gray-200 p-5"><p className="text-sm text-gray-500">Total counted support</p><p className="text-2xl font-bold text-green-700">{formatCurrency(data.total_counted_support)}</p></div><div className="bg-white rounded-2xl border border-gray-200 p-5"><p className="text-sm text-gray-500">Largest fairness gap</p><p className="text-2xl font-bold text-amber-700">{formatCurrency(data.largest_fairness_gap)}</p></div></div><div className="bg-white rounded-2xl border border-gray-200 p-5"><h2 className="font-semibold text-gray-900 mb-4">Counted support comparison</h2><div className="space-y-4">{data.children.map((child) => <div key={child.child_id}><div className="flex justify-between text-sm mb-1"><span className="font-medium text-gray-900">{child.child_name}</span><span>{formatCurrency(child.counted_total)} · Gap to highest {formatCurrency(child.gap_to_highest)}</span></div><div className="h-3 bg-gray-100 rounded-full overflow-hidden"><div className="h-full bg-blue-500" style={{ width: `${(Number(child.counted_total || 0) / max) * 100}%` }} /></div></div>)}</div></div><div className="bg-white rounded-2xl border border-gray-200 overflow-hidden"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="text-left p-3">Child</th><th className="text-right p-3">Allowance</th><th className="text-right p-3">Extra expenses</th><th className="text-right p-3">Large expenses</th><th className="text-right p-3">Excluded support</th><th className="text-right p-3">Rolling 12 months</th></tr></thead><tbody>{data.children.map((child) => <tr key={child.child_id} className="border-t border-gray-100"><td className="p-3 font-medium">{child.child_name}</td><td className="p-3 text-right">{formatCurrency(child.allowance_total)}</td><td className="p-3 text-right">{formatCurrency(child.extra_expense_total)}</td><td className="p-3 text-right">{formatCurrency(child.large_expense_total)}</td><td className="p-3 text-right">{formatCurrency(child.excluded_total)}</td><td className="p-3 text-right">{formatCurrency(child.rolling_12_month_total)}</td></tr>)}</tbody></table></div></div></FamilyLayout>
}