# Generated by Django 5.1.7 on 2026-07-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteTokenModuleAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("budget_tracker", "Budget Tracker"),
                            ("family_finances", "Family Finances"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_presets",
                        to="users.invitetoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invite Module Access",
                "verbose_name_plural": "Invite Module Access",
                "unique_together": {("invite", "module")},
            },
        ),
    ]
